name: guildy
description: Guildy omskrivning i Dart
version: 1.0.0
homepage: https://guildy.dk

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.3
  nyxx: ^2.0.0-rc.7
  nyxx_commander: ^2.0.0-rc.10
  nyxx_extensions: ^2.0.0-rc.7
  nyxx_interactions: ^2.0.0-rc.8
